services:
  backend:
    image: nikanostovan/personal_website_backend_test:latest
    container_name: PWB_TEST
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
